version: '3.8'
services:
  limancore:
    image: limancore:dev
    restart: always
    environment:
      # Redis settings
      - REDIS_HOST=liman-redis
      - REDIS_PASS=${DB_PASS}
      - REDIS_PORT=6379
      # DB settings
      - DB_HOST=liman-db
      - DB_DATABASE=liman
      - DB_USERNAME=liman
      - DB_PORT=5432
      - DB_PASS=${DB_PASS}
      # Nginx settings
      - PORT=443
    container_name: liman-core
    tty: true
    ports:
      - '443:443'
    volumes: 
      - core:/liman
      - certs:/usr/local/share/ca-certificates
    networks:
      - liman-net
    dns:
      - 127.0.0.1
  db:
    image: postgres:15
    container_name: liman-db
    restart: always
    environment:
      - POSTGRES_USER=liman
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=liman
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - liman-net
  redis:
    image: redis
    container_name: liman-redis
    environment:
      - REDIS_PASSWORD=${DB_PASS}
      - REDIS_DISABLE_COMMANDS=CONFIG
    command: > 
      --requirepass ${DB_PASS} --protected-mode yes
    networks:
      - liman-net
  webssh:
    image: limancore:webssh
    restart: always
    container_name: liman-webssh
    networks:
      - liman-net

volumes:
  # Persistent Postgresql Database
  db:
    driver: local
  # Persist Core Files
  core:
    driver: local
  # Persist Linux System Certificates
  certs:
    driver: local

networks:
  liman-net:
    name: liman-net
    driver: bridge