version: '3.8'
services:
  haproxy:
    image: haproxy:alpine
    container_name: liman-haproxy
    build: ./haproxy
    networks:
      - liman-net
    ports:
      - '443:443'
  limancore:
    image: limancore:master
    environment:
      - DB_PASS=${DB_PASS}
      - PORT=4443
    container_name: liman-core
    tty: true
    ports:
      - '4443:4443'
    volumes: 
      - core:/liman
      - certs:/usr/local/share/ca-certificates
    networks:
      - liman-net
    dns:
      - 127.0.0.1
  limancore2:
    image: limancore:master
    environment:
      - DB_PASS=${DB_PASS}
      - PORT=4444
    container_name: liman-core2
    tty: true
    ports:
      - '4444:4444'
    volumes: 
      - core:/liman
      - certs:/usr/local/share/ca-certificates
    networks:
      - liman-net
    dns:
      - 127.0.0.1
  db:
    image: postgres:15
    container_name: liman-db
    restart: always
    environment:
      - POSTGRES_USER=liman
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=liman
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - liman-net
  redis:
    image: redis
    container_name: liman-redis
    environment:
      - REDIS_PASSWORD=${DB_PASS}
      - REDIS_DISABLE_COMMANDS=CONFIG
    command: > 
      --requirepass ${DB_PASS} --protected-mode yes
    networks:
      - liman-net
  webssh:
    image: liman:webssh
    container_name: liman-webssh
    networks:
      - liman-net

volumes:
  # Persistent Postgresql Database
  db:
    driver: local
  # Persist Core Files
  core:
    driver: local
  # Persist Linux System Certificates
  certs:
    driver: local

networks:
  liman-net:
    name: liman-net
    driver: bridge